### PR TITLE
fix #64 - tickFactory regression

### LINKED ISSUE #64: tickFactory is no longer used (was recently removed)
Likely an accident, but this commit https://github.com/Netflix/ember-nf-graph/commit/2ecd7d884595323badc8d074708bf3c0f626f6b4 removed `tickFactory` from being applied. This affects argus as well (the ticks aren't as intended).

Cc/ @jeff3dx

### PR DESCRIPTION
**Pull request by blesh**
@jayphelps - please look at the unit tests for this. I had to get hacky, because I couldn't find a great way to mock the `uniq` and `alias` properties, so I ended up subclassing just to override those properties for my test. Works... but feels gross.

### CODE REVIEW

**Comment by blesh** [comment]
Merging anyhow, it was a simple fix... it's just the tests I think look weird... they work, as tests, but it seems like there should be a more idiomatic way to do this.

File: tests/unit/app/components/nf-y-axis-test.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+moduleForComponent('nf-y-axis', {
+  // specify the other units that are required for this test
+  needs: ['component:nf-graph']
+});
+
+test('nf-y-axis tickData should call tickFactory if available', function(assert) {
+  var args;
+
+  //HACK: couldn't find a great, documented way of mocking readonly and aliased propertied
```
Comment (jayphelps) [inline tests/unit/app/components/nf-y-axis-test.js]: I actually don't think this is hacky at all. Seems like a valid way to stub out what you need.
